name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake game
        uses: Platane/snk@v3
        with:
          github_user_name: KajetanKisielewski
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=#00c8ff
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00c8ff
            dist/github-snake.gif?palette=github-light&color_snake=#00c8ff&color_background=#ffffff
            dist/github-snake-dark.gif?palette=github-dark&color_snake=#00c8ff&color_background=#0d1117

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
